=== Обозначения
[%step]
. Эпоха -- stem:[E := \{e_i : i \in N, e_i < e_j \}]
. Лидер -- stem:[\Lambda:= \{\lambda_{e_1}... \lambda_{e_N}\} :  \lambda_{e_i} \prec \lambda_{e_j} \quad iff \quad  e_i < e_j ]
. Идентификатор транзакции -- stem:[zxid := <e_i, j>, j \in N ]
. Кворум -- stem:[Q \subseteq {s_1, s_2, ... s_N} : |Q| > N/2]
Транзакции распространяются лидером и фиксируются серверами.

=== Strong leadership
[%step]
. В любой момент времени может быть только **один лидер**
. Запросы на **изменения** данных перенаправляются и обрабатываются только **лидером**
. Запросы на изменения данных подтверждаются **кворумом**
. Перед подтверждением, транзакция записывается каждым сервером в
транзакционный журнал на диск (**transactional log**)
. Периодически происходит запись состояния реплицированной структуры данных в персистентную память
(**snapshot**)

=== Диаграмма состояний сервера
[plantuml, "zk_service_state"]
----
@startuml
[*] --> LOOKING
LOOKING -right-> LEADING
LEADING -left-> LOOKING
FOLLOWING -right-> LOOKING
LOOKING -left-> FOLLOWING
@enduml
----

=== ZAB. Лидер (LEADER)
[%step]
. При получении запроса на изменение от клиента или последователя:
.. Генерирует предложение (`PROPOSAL`) и отправляет последователям.
.. Синхронизирует данные в журнал транзакции и генерирует подтверждение от себя (`ACK`)
. При получении подтверждений (`ACK`) от кворума отсылает запрос `COMMIT` и изменяет у себя данные

[plantuml, "leader_zab"]
----
@startuml
hide empty description
state end1 <<end>>
state end0 <<end>>

[*] -right-> PrepRequestProcessor
PrepRequestProcessor -right-> ProposalRequestProcessor
ProposalRequestProcessor -right-> CommitRequestProcessor
CommitRequestProcessor -right-> ToBeAppliedProcessor
ToBeAppliedProcessor -right-> FinalRequestProcessor
FinalRequestProcessor -right-> end0
ProposalRequestProcessor -down-> SyncRequestProcessor
SyncRequestProcessor -right->AckRequestProcessor
AckRequestProcessor -right-> end1
@enduml
----

=== ZAB. Последователь (FOLLOWER)
[%step]
. При получении запроса на изменения от клиента:
.. Перенаправляет запросы на изменения лидеру
.. При получении `COMMIT` меняет структуру данных
. При получении предложения от лидера (`PROPOSAL`):
.. Синхронизирует данные в журнал транзакций
.. Шлет подтверждение лидеру (`ACK`)

[plantuml, "follower_zab_1"]
----
@startuml
hide empty description
[*] -right-> FollowerRequestProcessor
FollowerRequestProcessor -right-> CommitRequestProcessor
CommitRequestProcessor -right-> FinalRequestProcessor
FinalRequestProcessor -right-> [*]
@enduml
----
[plantuml, "follower_zab_2"]
----
@startuml
hide empty description
[*] -right-> SyncRequestProcessor
SyncRequestProcessor -right-> AckRequestProcessor
AckRequestProcessor -right-> [*]
@enduml
----

=== Выборы лидера (LEADER ELECTION)
[%step]
. Создаем свой голос stem:[v := \langle S_{id}, zxid\rangle]
. Отправляем голос другим серверам
. При получении голоса stem:[v' := \langle S'_{id}, zxid'\rangle] от другого сервера
.. Если stem:[zxid > zxid' \lor zxid = zxid', S_{id} > S'_{id}] то отправляем свой голос повторно
.. Иначе меняем свой голос на stem:[v']
. Продолжаем выборы пока не получим от всех серверов одинаковые голоса.

=== Синхронизация
[%step]
. Последователи от нового лидера получают
.. `DIFF` или `TRUNC` если нужно применить разность или отбросить транзакции с определенной stem:[zxid]
.. `SNAP` если последователь сильно отстал и надо применить полный снимок данных с лидера

=== ZAB (Гарантии)
** Если stem:[zxid < zxid'] и на каком-то произвольном сервере зафиксирована stem:[tx_{zxid'}], то на этом
сервере зафиксирована stem:[tx_{zxid}], причем stem:[tx_{zxid} \prec tx_{zxid'}].

=== Клиентские сессии
[%step]
* У клиентской сессии есть длительность (session timeout)
* Клиентские сессии отслеживаются лидером
* Клиентские сессии синхронизируются от последователя к лидеру каждые stem:[tick / 2]
* Клиент при отсутствии активности шлет пустые запросы на сервер, обновляя сессию.
* Клиент при переподключении к тому же или другому серверу может восстановить сессию в течении session timeout.
* Данные, привязанные к сессии очищаются лидером по инвалидации сессии.
